//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StenoCryptor.Web.Localization.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StenoCryptor.Web.Localization.Views.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no access for this page.
        /// </summary>
        public static string AccessError {
            get {
                return ResourceManager.GetString("AccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StenoCryptor is a web-applicatioin that aims to implement the best scientific researches into stenostography..
        /// </summary>
        public static string AppRepresentationText {
            get {
                return ResourceManager.GetString("AppRepresentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect DWM.
        /// </summary>
        public static string DetectDwm {
            get {
                return ResourceManager.GetString("DetectDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect result.
        /// </summary>
        public static string DetectResult {
            get {
                return ResourceManager.GetString("DetectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is DWM detected in your container. You can extract it if you wish..
        /// </summary>
        public static string DwmDetected {
            get {
                return ResourceManager.GetString("DwmDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no DWM detected in your container or it is brocken..
        /// </summary>
        public static string DwmNotDetected {
            get {
                return ResourceManager.GetString("DwmNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed DWM.
        /// </summary>
        public static string EmbedDwm {
            get {
                return ResourceManager.GetString("EmbedDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not selected or it is empty.
        /// </summary>
        public static string ErrPostFileIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ErrPostFileIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract DWM.
        /// </summary>
        public static string ExtractDwm {
            get {
                return ResourceManager.GetString("ExtractDwm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} is sucessfuly processed..
        /// </summary>
        public static string FileProcessed {
            get {
                return ResourceManager.GetString("FileProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_ {
            get {
                return ResourceManager.GetString("Home_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remains.
        /// </summary>
        public static string Remains {
            get {
                return ResourceManager.GetString("Remains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
    }
}
